added error

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,6 +1,10 @@
 
 #!/usr/bin/env bash
 echo "-----> Installing Wine for Electron"
+
+# fail if build fails
+set -e
+
 # parse and derive params
 BUILD_DIR=$1
 CACHE_DIR=$2
